# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
