# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
    ]
