# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_erreur',
            name='code_message',
            field=models.CharField(max_length=10, verbose_name='Code Message'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='code_message',
            field=models.CharField(max_length=10, verbose_name='Code Message'),
        ),
    ]
