# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sms_envoyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=160)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('id_message_recu', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sms_recu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('message_text', models.CharField(max_length=160)),
                ('id_message', models.IntegerField()),
                ('numero_court', models.IntegerField()),
                ('date_reception', models.CharField(max_length=10)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('mot_cle', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('telephone', models.IntegerField(default=0)),
                ('telephone2', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=20)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Lieu')),
            ],
        ),
    ]
