# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sport_favori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inscription.Sport'),
            preserve_default=False,
        ),
    ]
