# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='matricule',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
