# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passagers', '0002_auto_20160424_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passager',
            name='destination',
        ),
        migrations.AlterField(
            model_name='voyage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passagers.Destination'),
        ),
    ]
